### ISSUE TITLE
Add doc themes

### ISSUE THREAD

**Issue by dbuenzli** [b0-system/odig#21]
At least a dark one. But first the stylesheet should stabilize and the tool configuration problem should be solved.c

**Comment by rizo** [comment]
Do you think it would be possible, and does it makes sense at all, to separate the stylesheet into the structural parts and the actual styling? For some of my libraries I modify `odoc.css` inline but that doesn't seem like a good idea when I only want to make cosmetic changes.

**Comment by dbuenzli** [comment]
@rizo (and /cc @aantron @trefis) I'm not going to really care about that problem in `odig` itself. Basically I don't want to have to maintain contributed themes and/or deal with people's tastes, distastes, ideas about nice, font sizes and what not. 

So to live a simple life my plan is the following:

1. `odig` provides a mecanism that allows any `opam` package to install a css-theme and make it available to `odig` (see below).
2. `odig` implements an `odig css-theme (list|get|set)` command that lists, gets and changes the current theme for generated documentation.
3. The default `odig` css-theme will be the default `odoc` css as provided by `odoc` (see below) or the one defined via the `ODIG_ODOC_CSS_THEME` env var (if no theme was explicitely set via 2.).
4. (`odig` will maybe provides it's own light/dark themes that do suit *my* taste which I indeed do intent to metaprogram, but these *won't* be the default theme.)

## Regarding 1 

The plan is the following. Any `odig` recognized package PKG can install in `$(opam var PKG:doc)` a directory called `odoc-css-theme`. Every subdirectory name `sub` of this directory (i.e. every directory name `$(opam var PKG:doc)/odoc-css-theme/sub`) defines a theme identifier `PKG.sub` which is used by `odig css-theme` and `ODIG_ODOC_CSS_THEME` for specifying them. 

A theme is a whole subdirectory (so that it can include e.g. fonts) copied over at the root of the generated documentation directory. Actually maybe it would be nice if `odoc` refered to it's css from a toplevel subdir (e.g `odoc.css` -> `_theme/odoc.css`) so that we can simply replace the `_theme` dir to change the theme (we then don't need to keep track of the actual theme's files, something we need to do if we simply vomit the theme at the root dir).

Having that `odig-css-theme` directory in `PKG:doc` is maybe a bit dirty. Maybe it should rather live in `PKG:etc`, however currently `odig` only knows about `PKG:lib` and `PKG:doc` and I'm a bit lazy. Feel free to tell me that's unacceptable.

## Regarding 3
Regarding 3. some `odig` specific selectors related to indexes (mainly styling the stuff on [this](https://docs.mirage.io/) and [that section](https://docs.mirage.io/alcotest/index.html#info)) may need to be added to `odoc`, but I think we may be able to cast this as general indexing selectors (rather than `odig-` selectors) so that `odig` is not mentioned in `odoc`.

Comments/suggestions welcome.

**Comment by dbuenzli** [comment]
@rizo, it seems @aantron has not time at the moment to work on `odoc`. I now have a short opportunity to work on `odig`, if you have time could you maybe be give a hand for this to happen ? 

Basically to solve this in a clean a manner one needs to change the way `odoc` refers to and writes its `css` file and/or solve [this](https://github.com/ocaml/odoc/issues/4) `odoc` issue.

**Comment by rizo** [comment]
> @rizo, it seems @aantron has not time at the moment to work on odoc. I now have a short opportunity to work on odig, if you have time could you maybe be give a hand for this to happen ?

@dbuenzli sorry for the delay. I've been a bit busy at work lately, but I might be able to find some time, specially if this is blocking you.

Regarding your previous comments:

> odig provides a mecanism that allows **any** opam package to install a css-theme

Can you explain what is the motivation behind this? I understand you want flexibility in odig to avoid the issues you mentioned, but should this flexibility be given to _any_ package? Wouldn't a global configurable theme be enough to achieve this? My concrete concerns are:

- I think global theme configuration would be easier to implement with similar benefits. By default `odoc` could have the light and dark variants and anyone could add their own themes (like the `odig` theme in point 4).
- This can lead to significant styling inconsistencies across different packages in the same doc registry, if people go crazy with their CSS.
- I wouldn't consider having per package themes to be a high-priority feature (unless I'm missing something, of course). Specially because, if I understood correctly, you're proposing having support for multiple themes per package.

If you, in particular, want your packages to always (and for everyone) be rendered with your styling, regardless of the default or globallly set theme, I can understand that, but would argue that consistency is more desirable at this stage, specially for semi-official registries like <https://docs.mirage.io>. Local or external docs can use any desired theme with the global configuration.

> odig implements an odig odoc-theme (list|get|set) command that lists, gets and changes the current theme for generated documentation.

Am I correct in assuming `odig odoc-theme (list|get|set)` would operate on the global configuration as well as on the per-package basis (_e.g._ `odig odoc-theme set cmdliner.dark`)? How would you pick the default theme across the different per-package `PKG.sub` themes? Also what is the `get` command for in this case?

> so that we can simply replace the `_theme` dir to change the theme

What is the `_theme` dir and and where would it be replaced? Is it a symlink to the current theme?

> so that we can simply replace the _theme dir to change the theme (we then don't need to keep track of the actual theme's files, something we need to do if we simply vomit the theme at the root dir)

I agree, this already seems to be a bit painful. I'll follow your suggestion and implement the option 2 you mentioned [here](https://github.com/ocaml/odoc/issues/4#issuecomment-398738967).

>  some odig specific selectors related to indexes may need to be added to odoc

I think having `odig`-specific selectors in `odoc` is fine. We could make them generic or move the `odig` styling into a separte file, but from the theme-designer perspective both need to be taken into consideration anyway.

Sorry about the storm of questions. Let me know if I misunderstood something.

**Comment by dbuenzli** [comment]
> @dbuenzli sorry for the delay.

No worries

> Let me know if I misunderstood something.

Yes you did ;-), any package can install a theme to be chosen and used *globally* by the end-user; not every package can choose the theme it wants to be rendered in, that would be horrible.

The only thing I'm doing is piggy-backing on the `opam` packaging infrastructure to distribute themes.

> I agree, this already seems to be a bit painful. I'll follow your suggestion and implement the option 2 you mentioned here.

Yes, I think that should be enough (in order for me to solve all the `odig`, https://github.com/ocaml/odoc/issues/89 would be nice if you can have a look at it aswell).

**Comment by rizo** [comment]
> Yes you did ;-)

Then I’m glad I was wrong! Your last comment clarifies everything and your proposal makes sense.

I’ll continue the discussion on the respective odoc issues.

**Comment by dbuenzli** [comment]
Support for this is available on master. 

Theme installation structure is described [here](https://b0-system.github.io/odig/doc/odig/packaging.html#theme_install) and end user usage is [here](https://b0-system.github.io/odig/doc/odig/manual.html#odoc_themes).
