### ISSUE TITLE
Review warnings occuring with module aliases

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [b0-system/odig#38]
When I try and use `odig` right now, I get page after page of output like this, for every single global module I have installed:

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/200/45579677-599a1f00-b84f-11e8-8df0-9d9c6bc22252.png">

It's pretty clear that my opam installation isn't retaining the build-products it needs to, for `odig doc` to work properly; but I have no idea how to go about enabling this. I have `$OPAMKEEPBUILDDIR=true` and `$OCAMLPARAM="_,bin-annot=1"` in my setup [for Merlin](https://github.com/ocaml/merlin/wiki/Letting-merlin-locate-go-to-stuff-in-.opam); but that doesn't seem to be enough.

**Comment by dbuenzli** [comment]
Nothing should be done at the `opam` level. There's cooperation required from packages though and that's already documented in `odig help packaging` (will move that to a webpage in the next version). However `dune` should abide by them which I guess is what is used by `base`. 

The first lines are an annoying warning produced by `odoc` see https://github.com/ocaml/odoc/issues/158. 

The second ones may be due to a bug in the way `odig` proceeds in the presence of module aliases, I will have a look at a certain point. However could you just confirm me that you are not using the master version of `odoc`.

**Comment by ELLIOTTCABLE** [comment]
I … doubt it's a bug specific to Base; I get *literally hundreds* of terminal-pages of both kinds of output (I'd say probably *mostly* the second kind, though?)

Is there a way I can totally clear out my `odig` cache, re-run, and actually Gist all of the output? I don't know why I didn't do that in the first place. 🤣

**Comment by dbuenzli** [comment]
> I … doubt it's a bug specific to Base;

? I don't think I hinted that in what I wrote.

> Is there a way I can totally clear out my `odig` cache

`odig cache clear`, in general `odig --help` might help. 

Also you didn't tell me which `odoc` you are using but FWIW I also get these warnings I'll look in these at some point but essential is that documentation should get produced which at least here is the case.

**Comment by dbuenzli** [comment]
The whole driving logic has been redone on `master` as far as I can see this is no longer to be seen.
