### ISSUE TITLE
Empty pages with odoc 1.3.0

### ISSUE THREAD

**Issue by bluddy** [b0-system/odig#39]
Just as the title says -- odig produces only empty module pages currently.

**Comment by dbuenzli** [comment]
Well basically `odoc` was rewritten one more time and broke many things without any form of attention and cooperation with respect to `odig`'s usage --- which is a bit odd given that in practice it gives you an easy to use and very large and diverse test base.

The 1.3.0 release anyways changes the semantics of ocamldoc headers so I'm not planning on supporting it. Besides I have a rewrite of `odig` in the works, notably to make it much more efficient, but it got stalled because the `odoc` tool is largely broken at the moment, see the [recent issues](https://github.com/ocaml/odoc/issues?utf8=%E2%9C%93&q=is%3Aissue++author%3Adbuenzli+) I filed.

If you can find an easy patch against odig's current master to make it work I'll gladly integrate it and make a release. But as far as I'm concerned I have no time to loose with this and I suggest you to stick to previous versions of odoc for the time being.

**Comment by bluddy** [comment]
The 1.3.0 odoc version is quite an attraction in terms of looks and behavior, so if we can patch it into working that'll be great -- even with the pending rewrite.

**Comment by bluddy** [comment]
Also, efficiency doesn't seem to be a huge issue right now, so I'm not sure it's worth the rewrite...

**Comment by dbuenzli** [comment]
> Also, efficiency doesn't seem to be a huge issue right now,

I doubt.

**Comment by bluddy** [comment]
OK. I'd be interested to see how long it takes to process all of OPAM currently. My large selection of local OPAM seems pretty quick.

From what I can tell, the html files are being produced, it's just the index files that aren't produced properly.

**Comment by dbuenzli** [comment]
> OK. I'd be interested to see how long it takes to process all of OPAM currently. My large selection of local OPAM seems pretty quick.

On my machine with a large testing switch (which is far of all opam) it quickly came to about a minute with a previous version and I doubt this has actually changed. 

A little bit of parallelization will make that more bearable. Also dealing with install base changes is annoying at the moment much too much get recompiled (see #20, but the solution there is not what should be done). 

Nothing complex in handling that if `odoc` gives me the right tools. That is working `*-deps` and `*-target` commands and since my time to work on this is quite limited I rather wait for a decent `odoc` release before investing again time on this.

**Comment by dbuenzli** [comment]
Now that I remember @bluddy if you have time could maybe see if https://github.com/dbuenzli/odig/pull/36/ fixes the issue.

**Comment by bluddy** [comment]
Yeah that seems to do the trick.

**Comment by dbuenzli** [comment]
Ok thanks, I'll try to have a look integrating this when I get a bit of time.

**Comment by dbuenzli** [comment]
This is fixed on master a release will happen in the upcoming weeks. In case you are interested master needs a bit of juggling to get installed:

```
opam pin add b0 https://github.com/b0-system/b0.git#b00
opam pin add odoc --dev
opam pin add odig --dev
```
