### ISSUE TITLE
odig can't find browser on Mac 10.10

### ISSUE THREAD

**Issue by dubiousjim** [b0-system/odig#58]
Installed odig through opam (using ocaml 4.09.0) and commands like `odig readme odig` work fine (opening a pager in my Terminal).

But any command that wants to open a web browser fails with

```
$ odig doc odig
odig: [ERROR] find browser: default lookup: cmd ['/usr/bin/osascript' '-l' 'JavaScript' '-']: signaled [SIGSEGV]
```

The osascript binary passes a minimal check:

```
$ echo 1 | osascript -l JavaScript -
1
```

This may be related to the closed [issue #4 on dbuenzli/webbrowser](https://github.com/dbuenzli/webbrowser/issues/4), but the comments there lead nowhere.

Is there some way to tell odig by hand how to invoke my browser? Just using `open http://...` or `open file://...` will work. (I have a shell script that converts the latter into `osascript -e 'tell application "Chrome" to open location "file://..."'`.)

**Comment by dbuenzli** [comment]
See documentation of the `--browser` option in `odig doc --help`.

**Comment by dubiousjim** [comment]
Thanks! Setting `BROWSER` to `open` or `chrome` does this trick.

**Comment by dbuenzli** [comment]
Ok cool. If the error persist when you upgrade to say 10.12 and 10.13 please get in touch. I suspect this may be due to a bug in the objective-c bridge on 10.10. 

Basically it seems [this script](https://github.com/b0-system/b0/blob/5c5e6f02a7c447f09365786aa99af416b532964e/src-care/b0_www_browser.ml#L21-L23) segfaults on 10.10.
